name: app_systems
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  image_picker: ^0.8.4+4
  http: ^0.13.6
  intl: ^0.18.1
  signature: ^5.0.0
  duration_picker: ^1.2.0
  cupertino_icons: ^1.0.3  
  permission_handler: ^11.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/avarias.png
    - assets/config.json
